<Workspace Version="1.2.2.373" X="194.02791896821" Y="271.116765553031" zoom="0.971826874798003" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f7df56da-d237-48b2-ab10-0c0cb1c9e085" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Id" x="439.7187002716" y="126.251609837516" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Id">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="a286eb20-7898-47f4-b4a7-c925c4d03396" type="PythonNodeModels.PythonNode" nickname="Python Script" x="719.480063481003" y="132.985222578459" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
doc = DocumentManager.Instance.CurrentDBDocument
#doc = IN[1]
#unwrap incoming information for use with API
ids = []
for i in IN[0]:
    ids.append(UnwrapElement(i))
#use element ids to select elements
elements = []
for i in ids:
	#check if id is string
	if isinstance(i, str) and len(i) &lt;= 7:
		idInt = int(i)
		elemId = Autodesk.Revit.DB.ElementId(idInt)
		elements.append(doc.GetElement(elemId).ToDSType(True))
	elif isinstance(i, int):
		elemId = Autodesk.Revit.DB.ElementId(i)
		elements.append(doc.GetElement(elemId).ToDSType(True))
	elif isinstance(i, Autodesk.Revit.DB.ElementId):
		elements.append(doc.GetElement(i).ToDSType(True))
	elif isinstance(i, str) and len(i) &gt;= 8:
		elements.append(doc.GetElement(i).ToDSType(True))
	else:
		OUT = "invalid input"

#Assign your output to the OUT variable
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="beaa7ea9-f143-4f23-b38a-66c2716b00ac" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="124.87617094018" y="132.138005041469" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f7df56da-d237-48b2-ab10-0c0cb1c9e085" start_index="0" end="a286eb20-7898-47f4-b4a7-c925c4d03396" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="beaa7ea9-f143-4f23-b38a-66c2716b00ac" start_index="0" end="f7df56da-d237-48b2-ab10-0c0cb1c9e085" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>